### ISSUE TITLE
Tools Build.c error

### ISSUE THREAD

**Issue by hellocyf** [jbruchon/elks#1]
make[3]: Entering directory `/private/var/root/elks-git/elks/arch/i86/tools'
gcc -I ../../../include -o build build.c
WARNING: Invalid path ignored:
build.c:26:55: error: sys/sysmacros.h: No such file or directory
make[3]: **\* [build] Error 1

**Comment by jbruchon** [comment]
What is the context of this error? What commands did you run to produce it?

**Comment by hellocyf** [comment]
build failed on ipad3.
and works fine on pc.

**Comment by jbruchon** [comment]
Building outside of an i386 or x86_64 GNU/Linux environment is not currently supported.

**Comment by mfld-fr** [comment]
Sorry for the mixing of the issues, latest commits actually related to mfld-fr#1, not this one.
