### ISSUE TITLE
Elkscmd build fail

### ISSUE THREAD

**Issue by hellocyf** [jbruchon/elks#2]
I have build elks and make boot image.
I want to make image with root system,so goto Elkscmd 
Make images.zip,this makes error .

:~/elks/elkscmd$ sudo make images.zip
cp /home/xxx/elks/elks/arch/i86/boot/Image boot
make[1]: Entering directory `/home/xxx/elks/elkscmd'
/bin/sh: 1: [[: not found
/bin/sh: 1: -e: not found
-e

 **\* Do builds in dev86 and dev86/bootblocks first ***

make[1]: **\* [boot_blocks] Error 1
make[1]: Leaving directory `/home/xxx/elks/elkscmd'
make: **\* [comb] Error 2

**Comment by hellocyf** [comment]
rebuild dev86

make[3]: `bcc' is up to date.
make[3]:`ncc' is up to date.
make[3]: `bcc-cc1' is up to date.
make[3]: Leaving directory`~/elks/dev86/bcc'
cp -p bcc/bcc bin/Bcc
cp -p bcc/ncc bin/ncc
cp -p bcc/bcc-cc1 lib/bcc-cc1
make -C cpp CC='cc' CFLAGS=' -O2 -fno-strict-aliasing' LDFLAGS='' PREFIX=/usr LIBDIR='/usr/lib/bcc' BINDIR='/usr/bin' ANSI='' bcc-cpp
make[3]: Entering directory `~/elks/dev86/cpp'
gperf -aptTc -N is_ctok -H hash1 token1.tok > tmp.h
token1.tok:10: declarations are not allowed in the keywords section.
To declare a keyword starting with %, enclose it in double-quotes.
make[3]: *** [token1.h] Error 1
make[3]: Leaving directory`~/elks/dev86/cpp'
make[2]: **\* [cpp] Error 2
make[2]: Leaving directory `~/elks/dev86'
make[1]: *** [all] Error 2
make[1]: Leaving directory`~/elks/dev86'
make: **\* [all] Error 2

token1.tok
struct token_trans { char \* name; int token; };
%%
...,    TK_ELLIPSIS

> > =,    TK_RIGHT_ASSIGN
> > <<=,    TK_LEFT_ASSIGN
> > +=, TK_ADD_ASSIGN
> > -=, TK_SUB_ASSIGN
> > *=, TK_MUL_ASSIGN
> > /=, TK_DIV_ASSIGN
> > %=, TK_MOD_ASSIGN
> > &=, TK_AND_ASSIGN
> > ^=, TK_XOR_ASSIGN
> > |=, TK_OR_ASSIGN
> > , TK_RIGHT_OP
> > <<, TK_LEFT_OP
> > ++, TK_INC_OP
> > --, TK_DEC_OP
> > ->, TK_PTR_OP
> > &&, TK_AND_OP
> > ||, TK_OR_OP
> > <=, TK_LE_OP
> > =, TK_GE_OP
> > ==, TK_EQ_OP
> > !=, TK_NE_OP
> > .., TK_WORD

os unbuntu 14.04.

**Comment by jbruchon** [comment]
It seems as if you are having problems due to the default shell (/bin/sh) on Debian-based distributions not being GNU Bash (they use dash instead). The [[ command is a shell builtin which is an alias for the test command. I should also point out that I have not personally tested "make images.zip" and do not know if it currently works.

**Comment by hellocyf** [comment]
boot_blocks: $(FD_BSECT) $(KHELPER)
    @if [[ ! -e $(MINIX_BOOT)/minix.bin || ! -e $(MINIX_BOOT)/minix_elks.bin ]]; \
    then echo -e "\n\n **\* Do builds in dev86 and dev86/bootblocks first **\* \n\n"; exit 1; fi
I delete boot_blocks in _build_bootable_target like below
_build_bootable_target: _build_target kernel_image
it's works!
